//global
export const SAVE_USER = 'SAVE_USER';
export const SAVE_NUM_OF_UNREAD = 'SAVE_NUM_OF_UNREAD';
export const LOGIN = 'LOGIN';
export const FETCH_USER = 'FETCH_USER';
export const SAVE_COINS = 'SAVE_COINS';
export const LOGOUT = 'LOGOUT';
export const RESET_USER = 'RESET_USER';
export const SIGN_UP = 'SIGN_UP';

//loading
export const SAVE_LOADING = 'SAVE_LOADING';

//followers
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const FETCH_OLD_FOLLOWERS = 'FETCH_OLD_FOLLOWERS';
export const FETCH_NUM_OF_FOLLOWER = 'FETCH_NUM_OF_FOLLOWER';
export const SAVE_FOLLOWERS = 'SAVE_FOLLOWERS';
export const SAVE_OLD_FOLLOWERS = 'SAVE_OLD_FOLLOWERS';
export const SAVE_NUM_OF_FOLLOWER = 'SAVE_NUM_OF_FOLLOWER';
export const RESET_FOLLOWERS = 'RESET_FOLLOWERS';
export const TOGGLE_FOLLOWERS_HASMORE = 'TOGGLE_FOLLOWERS_HASMORE';

//followings
export const FETCH_FOLLOWINGS = 'FETCH_FOLLOWINGS';
export const FETCH_OLD_FOLLOWINGS = 'FETCH_OLD_FOLLOWINGS';
export const FETCH_NUM_OF_FOLLOWING = 'FETCH_NUM_OF_FOLLOWING';
export const SAVE_FOLLOWINGS = 'SAVE_FOLLOWINGS';
export const SAVE_OLD_FOLLOWINGS = 'SAVE_OLD_FOLLOWINGS';
export const SAVE_NUM_OF_FOLLOWING = 'SAVE_NUM_OF_FOLLOWING';
export const RESET_FOLLOWINGS = 'RESET_FOLLOWINGS';
export const TOGGLE_FOLLOWINGS_HASMORE = 'TOGGLE_FOLLOWINGS_HASMORE';

//transactions
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_OLD_TRANSACTIONS = 'FETCH_OLD_TRANSACTIONS';
export const SAVE_TRANSACTIONS = 'SAVE_TRANSACTIONS';
export const SAVE_OLD_TRANSACTIONS = 'SAVE_OLD_TRANSACTIONS';
export const RESET_TRANSACTIONS = 'RESET_TRANSACTIONS';
export const BUY_COINS = 'BUY_COINS';
export const SAVE_TRANSACTIONS_HASMORE = 'SAVE_TRANSACTIONS_HASMORE';

//coin policy
export const FETCH_COIN_POLICY = 'FETCH_COIN_POLICY';
export const SAVE_COIN_POLICY = 'SAVE_COIN_POLICY';
export const RESET_COIN_POLICY = 'RESET_COIN_POLICY';

//messenger popover
export const FETCH_MESSENGER_POPOVERS = 'FETCH_MESSENGER_POPOVERS';
export const FETCH_OLD_MESSENGER_POPOVERS = 'FETCH_OLD_MESSENGER_POPOVERS';
export const SAVE_MESSENGER_POPOVERS = 'SAVE_MESSENGER_POPOVERS';
export const SAVE_OLD_MESSENGER_POPOVERS = 'SAVE_OLD_MESSENGER_POPOVERS';
export const RESET_MESSENGER_POPOVERS = 'RESET_MESSENGER_POPOVERS';

//notification popover
export const FETCH_NOTIFICATION_POPOVERS = 'FETCH_NOTIFICATION_POPOVERS';
export const FETCH_OLD_NOTIFICATION_POPOVERS = 'FETCH_OLD_NOTIFICATION_POPOVERS';
export const SAVE_NOTIFICATION_POPOVERS = 'SAVE_NOTIFICATION_POPOVERS';
export const SAVE_OLD_NOTIFICATION_POPOVERS = 'SAVE_OLD_NOTIFICATION_POPOVERS';
export const RESET_NOTIFICATION_POPOVERS = 'RESET_NOTIFICATION_POPOVERS';

//notification popover
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_OLD_NOTIFICATIONS = 'FETCH_OLD_NOTIFICATIONS';
export const SAVE_NOTIFICATIONS = 'SAVE_NOTIFICATIONS';
export const SAVE_OLD_NOTIFICATIONS = 'SAVE_OLD_NOTIFICATIONS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';

//conversation 
export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const SAVE_CONVERSATIONS = 'SAVE_CONVERSATIONS';
export const FETCH_OLD_CONVERSATIONS = 'FETCH_OLD_CONVERSATIONS';
export const SAVE_OLD_CONVERSATIONS = 'SAVE_OLD_CONVERSATIONS';
export const RESET_CONVERSATIONS = 'RESET_CONVERSATIONS';

//messages
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SAVE_MESSAGES = 'SAVE_MESSAGES';
export const FETCH_OLD_MESSAGES = 'FETCH_OLD_MESSAGES';
export const SAVE_OLD_MESSAGES = 'SAVE_OLD_MESSAGES';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER';
export const RESET_MESSAGES = 'RESET_MESSAGES';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';
export const FINISH_FETCH_OLD_MESSAGES = 'FINISH_FETCH_OLD_MESSAGES';
